const mongoose=require('mongoose');
const orderSchema=new mongoose.Schema({
   shippingInfo:{
       address:{
           type:String,
           required:true,
       },
       city:{
           type:String,
           required:true
       },
       state:{
           type:String,
           required:true,
       },
       country:{
           type:String,
           required:true,
       },
       pincode:{
           type:Number,
           required:true,
       },
       phone:{
           type:Number,
           required:true
       }
   },
   user:{
    type:mongoose.Schema.ObjectId,
    ref:"User",
    require:true
   },
   orderItems:[{
       name:{
           type:String,
           required:true,
       },
       product:{
           type:mongoose.Schema.ObjectId,
           ref:"Product",
           require:true,
       },
       image:{
           type:String,
           require:true
       },
       quantity:{
           type:Number,
           require:true,
       },
       price:{
           type:Number,
           require:true,
       }
   }],
   paymentInfo:{
       id:{
           type:String,
           require:true,
       },
       status:{
           type:String,
           require:true
       },
   },
   paidAt:{
       type:Date,
       required:true,
   },
   itemsPrice:{
       type:Number,
       required:true,
       default:true,
   },
   taxPrice:{
       type:Number,
       required:true,
       default:true,
   },
   shippingPrice:{
       type:Number,
       required:true,
       default:true,
   },
   totalPrice:{
       type:Number,
       required:true,
       default:true,
   },
   orderStatus:{
       type:String,
       required:true,
       default:"Processing"
   },
   deliveredAt:Date,
   createdAt:{
       type:Date,
       default:Date.now
   }

   
});
module.exports=mongoose.model('Order',orderSchema);